name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 配置Golang环境
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.18"
      - run: |
          go env -w GO111MODULE=on
          go version

      # 配置Node环境
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: node -v
      - run: yarn -v

      # 检出代码
      - name: Checkout Trigger Branch
        uses: actions/checkout@v2

      # 执行构建脚本
      - name: Excute Build Script
        run: yarn && yarn build

      # 列出产物
      - name: List output
        run: ls -lh ./output

      

      # 上传构建产物到发布
      - name: Upload Build Outputs
        uses: softprops/action-gh-release@v0.1.7
        with:
          tag_name: ${{ steps.get-version.outputs.VERSION }}
          name: Release ${{ steps.get-version.outputs.VERSION }}
          files: |
            ./output/gofi-linux-amd64
            ./output/gofi-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
